# Generated by Django 5.0.3 on 2024-05-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_URL", models.URLField(max_length=700)),
                ("short_url", models.CharField(max_length=200)),
                ("time_date_created", models.DateTimeField()),
            ],
        ),
    ]
